### ISSUE TITLE
sometimes it generates uuid out of order

### ISSUE THREAD

**Issue by robertorp** [mareek/UUIDNext#12]
![image](https://github.com/user-attachments/assets/e106cfd9-c964-40a4-984d-3cb8d2965e17)

I want to understand if this is really the case or if it is something I am doing wrong, I use postgres 15.5

Code,
![image](https://github.com/user-attachments/assets/5a80ba26-5830-4ef3-9b59-7cbcd4605f1c)

![image](https://github.com/user-attachments/assets/0ab8c3fb-823a-4b28-ac60-1e63b1e3e572)

![image](https://github.com/user-attachments/assets/72ae37b2-06bc-4fe1-bd9d-d31d45e1ccea)

**Comment by mareek** [comment]
In the screenshot you provided, the UUID order seems consistent with the "numero" and "data_operacao" columns.

Can you execute the same SQL query but ordered by data_operacao to see if there any problem, please ?

P.S. can you also provide the result as text instead of images ? it's way easier to analyze

**Comment by robertorp** [comment]
[vendas_202408080812.csv](https://github.com/user-attachments/files/16542096/vendas_202408080812.csv)

line 1808 of the file I sent starts using the library

in what I sent there is 2190 and it jumps to 2189, I really don't understand how it works if it's really like that sometimes it gives this, now a CSV file with the cycle of this entire client, I started using the library recently. It may be that some Guid V4 appears

**Comment by mareek** [comment]
Seeing the csv file you sent, it seems that you didn't put any "order by" clause in  the SQL query used to generate this file. 
The SQL language does not guarantee any order for the result if you don't put any "order by" clause in your select query.

I've looked at your csv file and the UUIDs seems in sync with the data_operacao column. I don"t see any issue here

**Comment by robertorp** [comment]
Okay, I get it, I thought everyone should allocate correctly in a SQL without order by or where one below the other, I'm not good with databases, I've been an ORM user all my life. We can close this.
