### ISSUE TITLE
Question: Is there a way to create UUIDv7 from specific DateTime(Offset)?

### ISSUE THREAD

**Issue by jdvor** [mareek/UUIDNext#14]

**Comment by mareek** [comment]
Currently there is no way to create a UUIDv7 from a specific dateTemie without using reflection in UUIDNext.

What would you use this for ?

**Comment by mareek** [comment]
I understand your use case and I think there may be many similar situations where a function to generate an UUIDv7 for a specific dateTime might be useful.

I have to think of a way to add this to UUIDNext's API in a way that's simple, hard to misuse and that doesn't break the sub-millisecond ordering mechanism.

**Comment by jdvor** [comment]
I think it's about surfacing this [method](https://github.com/mareek/UUIDNext/blob/main/Src/UUIDNext/Generator/UuidV7Generator.cs#L17), although for an API I would rather choose `DateTimeOffset` to avoid ambiguity of DateTimeKind.

I don't think there's any danger if it is used with a less precise DateTimeOffset than it would be otherwise obtained by DateTimeOffset.UtcNow. Yes, the resulting Guid may have more zeros around the 2nd byte, but clearly, the ones using the method with a time argument value time ordering slightly more than "uniqueness,"  which is still high in most use cases.

It would suffice to warn the user not to generate millions of Guids at the same time, perhaps in an XML comment.

Should I close the ticket / question or do you want it to remain open?

**Comment by mareek** [comment]
It's more complex than just giving access to UuidV7Generator.New(DateTime). 
To guarantee that UUID are always increasing, the generator has some logic to handle overflow, computer clock update, leap second, etc. that won't well if it is given random dateTimes as input.

BTW, I try to follow the ["pit of success"](https://ricomariani.medium.com/the-pit-of-success-cfefc6cb64c8) philosophy for this library, so when I introduce a new feature, I want to make sure that the library user won't use it in the intended way

**Comment by mareek** [comment]
Hi @jdvor,
I've released [a new beta version](https://www.nuget.org/packages/UUIDNext/4.0.0-beta) that allow to create a UUID v7 based on a specific DateTimeOffset by using the `UUIDNext.Tools.UuidToolkit.CreateUuidV7FromSpecificDate(DateTimeOffset)` method.

Can you try it and tell me if it responds to your needs ?

Thanks in advance
