### ISSUE TITLE
Allow construction of UUID7 with timestamp and random components

### ISSUE THREAD

**Issue by nimesh-notifi** [mareek/UUIDNext#15]
It looks like generation based off of a timestamp is allowed, but no ability to provide the entropy component. 
Scenario: You're generating a UUID based off of a hash of some values so that you have consistent output of UUIDs for certain combinations of data that you'd like to use the UUID to also check for duplicates on. 
Having a public method UUID7.Create(DateTime, byte[]) would allow producing the same UUID every time for the set of input params.

**Comment by mareek** [comment]
If you want hash based UUID I would recommend the use of UUIDv5 (Uuid.NewNameBased in UUIDNext)
