### ISSUE TITLE
Love the repo, but.

### ISSUE THREAD

**Issue by tomarks** [mareek/UUIDNext#3]
Some developers will need to run the licence past key stakeholders in thier company, some (snowflakes) of which might be offended by what they read.

**Comment by tomarks** [comment]
Didnt realise this was such a widely used licence. Still, could just use GPL or MIT, some devs might just see the strange licence as a joke and this might be a barrier to your library bieng adopted.

**Comment by mareek** [comment]
The WTFPL is a very permissive license, so if anybody is shocked by the wording of the license, they can fork this repo an replace the license with something else
