### ISSUE TITLE
UuidV8SqlServerGenerator?

### ISSUE THREAD

**Issue by osexpert** [mareek/UUIDNext#5]
I am confused. There is a file UuidV8SqlServerGenerator.cs and it seems that it means that v8 has anything to do with sql server. But the specs says v8 is for implementation specific data:
https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#name-uuid-version-8
"The only explicitly defined bits are the Version and Variant leaving 122 bits for implementation specific"

**Comment by osexpert** [comment]
Your docs says:
"UUIDNext
A fast and modern .NET library to generate UUID/GUID that are either sequential and database friendly (versions 7 & 8), name based (versions 5) or random (version 4)."
But according to spec, it is version 6 and 7 that are database friendly.

**Comment by osexpert** [comment]
Here is how v8 looks like in the spec:
  0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                           custom_a                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |          custom_a             |  ver  |       custom_b        |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |var|                       custom_c                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                           custom_c                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

The one in UuidV8SqlServerGenerator.cs looks like this:
            /* This structure should produce ordered UUIDs in SQL Server
              0                   1                   2                   3
              0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
             +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
             |                              rand                             |
             +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
             |             rand              |  ver  |         rand          |
             +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
             |var|         sequence          |          unix_ts_ms           |
             +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
             |                           unix_ts_ms                          |
             +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
             */

It is a bit confusing IMO.......

**Comment by peschkaj** [comment]
SQL Server's `UNIQUEIDENTIFIER` is not implemented as a UUID and sorts differently. To get proper sorting of UUIDs you need to rearrange the data. [Raymond Chen covers it well over here](https://devblogs.microsoft.com/oldnewthing/20190426-00/?p=102450).

**Comment by osexpert** [comment]
Sorry, I don't understand. But do you know if ms sql NEWSEQUENTIALID is the same as Version7 UUID's? In case I don't see any reason to use anything else than NEWSEQUENTIALID in ms sql and version7 in code.

But should there also not be a way to create v8 UUID that take 122 bits if custom data, like the spec says?
Currently there only seem to be an implementation of version8 included (UuidV8SqlServerGenerator), but not the Version8 itself?

**Comment by osexpert** [comment]
Also I see windows has a function, UuidCreateSequential in rpcrt4.dll that is different from ms sql NEWSEQUENTIALID. Do you know what UUID version UuidCreateSequential in rpcrt4.dll correspond to? Maybe none...
It is confusing...

**Comment by osexpert** [comment]
"UUID Version 7 and 8 are intended to be used as a primary key in a database"
I don't get this understanding when reading the spec. It says v8 is for testing and custom data. So it can be used for anything, and UUIDNext uses v8 with custom data to create some ms sql uuid variant. So I think this confuses the matter even more.

**Comment by osexpert** [comment]
I tried to generate some UUID with NEWSEQUENTIALID:
Looked like: 
E7FA7E3E-A811-EE11-BD14-782BCBAE1BCE
E8FA7E3E-A811-EE11-BD14-782BCBAE1BCE
E9FA7E3E-A811-EE11-BD14-782BCBAE1BCE

With UuidV8SqlServerGenerator:
c6521d0b-2890-83ce-8279-0188e795395c
77a86265-f5b0-8123-81de-0188e795395c
2a3b3f63-5860-8020-8267-0188e795395d

Does not look like they use the same algoritm.

**Comment by osexpert** [comment]
Here is someone that has tested index fragmentation in ms sql based on different Guid's.
https://www.mssqltips.com/sqlservertip/6595/sql-server-guid-column-and-index-fragmentation/

Should probably test UuidV8SqlServerGenerator and see how it compares to NEWSEQUENTIALID.
I will see if I get time to test this some time.

I see NEWSEQUENTIALID create nonstandard Guid's, currently claim to be version 14 (I guess it can change over time).
So UuidV8SqlServerGenerator is an improvement there, using real standard UUID's.
So I am guessing, maybe NEWSEQUENTIALID is a bit faster (create less index fragmentation) but with a huge disadvantage that it uses nonstandard UUID's.

Thanks.

**Comment by osexpert** [comment]
But still I wonder, when I look at NEWSEQUENTIALID vs UuidV8SqlServerGenerator, NEWSEQUENTIALID only changes the front of the UUID (good) while UuidV8SqlServerGenerator changes much more.
What about an UUID that was based on the logic NEWSEQUENTIALID uses but just smash variant 8 over it (since variant 8 is 122 bits of custom data + variant1 + version8)
Like:
byte[] msSqlSequential = NEWSEQUENTIALID;
SetVersion(ref msSqlSequential, 1);
SetVariant(ref msSqlSequential, 8);

It would create a Guid as close as possible as the most optimal (assumed) NEWSEQUENTIALID.

**Comment by mareek** [comment]
As reported in issue #2, UUID version 6 & 7 are not sorted properly in SQL Server. The reason is that the sorting of SQL Server's UNIQUEIDENTIFIER is based on UUID Version 1 (timestamp + mac address).
So I took advantage of the fact that "UUID version 8 provides an RFC-compatible format for experimental or **vendor-specific use cases**" to generate UUIDs that are both RFC compatible and properly sorted in SQL Server.

My goal is to make this library as simple as possible to use while producing standard and optimal UUID for each scenario.

I will add some comment in UuidV8SqlServerGenerator to explain why it was implemented that way.

**Comment by mareek** [comment]
> Also I see windows has a function, UuidCreateSequential in rpcrt4.dll that is different from ms sql NEWSEQUENTIALID. Do you know what UUID version UuidCreateSequential in rpcrt4.dll correspond to? Maybe none... It is confusing...

The windows's UuidCreateSequential Creates UUIDs Version 1 and SQL Server's NEWSEQUENTIALID "is a wrapper over the Windows UuidCreateSequential function, with some byte shuffling applied" ([see the docs](https://learn.microsoft.com/en-us/sql/t-sql/functions/newsequentialid-transact-sql)). So both functions create share some properties that may be problematic:
- they contain the mac address of the computer where they were generated
- the value they generate are predictable based on previous values
Therefore Microsoft explicitly discourage using these function if privacy is a concern.

UUID Vesrion 6, 7 and my implementation of Version 8 replace the mac address by random data to fix those problems

**Comment by osexpert** [comment]
Thanks guys. This is probably a documentation\information thing and not technical. A lot of different concepts and names (and I have not even mentioned COMB GUID yet :-D) But I will do testing to try to find\check\verify the sequential-ness of UuidV8SqlServerGenerator.

**Comment by osexpert** [comment]
Initial test:

```

CREATE TABLE [dbo].[GuidTest](
	[Guid] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_GuidTest] PRIMARY KEY CLUSTERED 
(
	[Guid] ASC
))
```

Code:
```
			var conn = new SqlConnection("Data Source=(local)\\mySqlServer;Initial Catalog=test; Integrated Security=sspi;TrustServerCertificate=true;");
			conn.Open();

			var comm = new SqlCommand("insert into GuidTest(Guid) values(@Guid)", conn);
			var prmGuid = comm.Parameters.Add("@Guid", System.Data.SqlDbType.UniqueIdentifier);

			var commLast = new SqlCommand("select top 1 Guid from GuidTest order by Guid desc", conn);

			int notLast=0;
			int last=0;

			for (int i = 0; i < 100000; i++)
			{
				var mssqlGuid = new UUIDNext.Generator.UuidV7Generator().New();
				prmGuid.Value = mssqlGuid;
				comm.ExecuteNonQuery();

				var lastG = (Guid)commLast.ExecuteScalar();
				if (lastG != mssqlGuid)
					notLast++;
				else
					last++;
			}

			Console.WriteLine($"Last: {last}, NotLast: {notLast}");
```

Result: Last: 13, NotLast: 99987

```
SELECT OBJECT_NAME(ips.OBJECT_ID)
 ,i.NAME
 ,ips.index_id
 ,index_type_desc
 ,avg_fragmentation_in_percent
 ,avg_page_space_used_in_percent
 ,page_count
FROM sys.dm_db_index_physical_stats(DB_ID(), NULL, NULL, NULL, 'SAMPLED') ips
INNER JOIN sys.indexes i ON (ips.object_id = i.object_id)
 AND (ips.index_id = i.index_id)
ORDER BY avg_fragmentation_in_percent DESC
```

avg_fragmentation_in_percent: 98,75

Hmm...this looks not so good, unless I am doing something wrong.

**Comment by peschkaj** [comment]
I'll leave it you to demonstrate where the fragmentation is (empty space in the page or unordered pages in the b-tree) and whether or not it's a performance problem (spoiler: fragmentation is never the performance problem, it's just something DBAs can control).

**Comment by osexpert** [comment]
And finally by using NEWSEQUENTIALID()
Last: 100000, NotLast: 0
avg_fragmentation_in_percent: 1,29032258064516
But yes, NEWSEQUENTIALID() has problems of its own, so its not really an option.
But maybe I can try to invent yet another Guid variant :-D
Jeje, it was fun :-)

**Comment by osexpert** [comment]
"I'll leave it you to demonstrate where the fragmentation is ...and whether or not it's a performance problem"
I have been using regular Guid's like "forever" and will probably continue for a long time. Never really noticend any problems with it. But since we all know it is "broken" I am constantly on the lookout for a good\perfect replacement\successor.

**Comment by osexpert** [comment]
But I forgot Guid.NewGuid()!
Last: 5, NotLast: 99995
avg_fragmentation_in_percent:99,1614255765199
WOW, thats really bad

**Comment by mareek** [comment]
> I _am_ doing something wrong. I used the wrong generator! Here is with UuidV8SqlServerGenerator: Last: 64933, NotLast: 35067 avg_fragmentation_in_percent: 47,2222222222222

Can you change your code to use `UUIDNext.Uuid.NewDatabaseFriendly(Database.SqlServer)` instead of `new UUIDNext.Generator.UuidV8SqlServerGenerator().New()` ?

The generators are not supposed to be created each time you create a new UUID

**Comment by osexpert** [comment]
With UUIDNext.Uuid.NewDatabaseFriendly(Database.SqlServer):
Last: 100000, NotLast: 0
avg_fragmentation_in_percent: 1,29032258064516
Quite a difference! Maybe a bit sensitive to misuse.

**Comment by mareek** [comment]
> With UUIDNext.Uuid.NewDatabaseFriendly(Database.SqlServer): Last: 100000, NotLast: 0 avg_fragmentation_in_percent: 1,29032258064516 Quite a difference! Maybe a bit sensitive to misuse.

Thank you for your tests !
They confirm that my implementation of UUID V8 gives the same results as NEWSEQUENTIALID without the problems of UUID Version 1.

I close this issue and I will open another one to add some comment on the implementation choices of UuidV8SqlServerGenerator and prevent misuses of the generators.

**Comment by osexpert** [comment]
My first test made a generator every time so not representative. Here it a new test for Version7:
UUIDNext.Uuid.NewDatabaseFriendly(Database.Other)
Last: 10, NotLast: 99990
avg_fragmentation_in_percent: 98,5477178423237
But there is nothing exiting about this:-)
And that was hopefully the end of this issue :-D
