### ISSUE TITLE
Is toByteArray outputting the correct format?

### ISSUE THREAD

**Issue by GunboatDiplomat** [mareek/UUIDNext#7]
If I understood correctly, GUID type is low endian, and UUIDv7 spec is big endian which means that toByteArray() will be wrong for NewDatabaseFriendly(Database.SQLite), but not for NewDatabaseFriendly(Database.SqlServer) which is UUIDv8 LE. Is that correct? If so, maybe there should be a disclaimer somewhere in the readme.

Also, is it possible to make all UUIDs represented correctly once https://github.com/dotnet/runtime/pull/87993 is merged, probably for NET8?

**Comment by mareek** [comment]
It's a bit more complicated than that. 
As explained by [Raymond Chen in this post](https://devblogs.microsoft.com/oldnewthing/20190426-00/?p=102450), GUID in Windows are stored as a structure composed of an int32 field, two int16 fields and an array of 8 bytes ([the structure in .NET is similar](https://github.com/dotnet/runtime/blob/f8cb3c760030ec9443d0d01d3f3ffd31fb92d9f7/src/libraries/System.Private.CoreLib/src/System/Guid.cs#L33)). The ToByteArray method just put this structure in a byte array using little endian encoding for each field of the structure; so as explained in [Microsoft's documentation](https://learn.microsoft.com/en-us/dotnet/api/system.guid.tobytearray#remarks) the result is neither a big endian neither a little endian reprensation of the UUID.

**Comment by mareek** [comment]
I can maybe add an extension method to the Guid type that output a byte array that reflects the string representation of the UUID.

**Comment by GunboatDiplomat** [comment]
Maybe it won't be needed, because according to this [comment ](https://github.com/dotnet/runtime/issues/88290#issuecomment-1618949425) Guid toByteArray with bigEndian: true flag (NET 8) should be able to correctly format uuid v7.
