### ISSUE TITLE
New license suggestion

### ISSUE THREAD

**Issue by pilouk** [mareek/UUIDNext#8]
Hi, your project is really nice and I would like to use this at our company but the current license choice may not be perceived as the most professional option.

Would it be possible to use a more commonly used open-source project licensee like MIT ?

Thank you!

**Comment by mareek** [comment]
Hi, 
The WTFPL is a very permissive license so if its presence prevents you from using UUIDNext in your company, you can fork the repository and replace it with the license of your choice.

**Comment by mareek** [comment]
Hi, 
The WTFPL is a very permissive license so if its presence prevents you from using UUIDNext in your company, you can fork the repository and replace it with the license of your choice.
